# Generated by Django 4.2.13 on 2024-05-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reps', models.IntegerField(default=10)),
                ('sets', models.IntegerField(default=4)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
