# Generated by Django 4.2.13 on 2024-05-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
    ]
