# Generated by Django 4.2.13 on 2024-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_alter_program_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='move',
        ),
        migrations.AddField(
            model_name='program',
            name='move',
            field=models.ManyToManyField(to='gymapp.move'),
        ),
    ]
